baseURL = "https://fifionachow.github.io"
publishDir = "docs"
title = "Fiona Chow"

languageCode = "en-uk"

theme = "hugo-coder"

[params]
    author = "Fiona Chow"
    info = "Data Scientist"
    description = "My learning journey"
    keywords = "blog,datascientist,personal,learning"
    avatarurl = "images/profile_picture.jpg"

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false
    since = 2020

    rtl = false

    math = true
    # custom_css = ["css/custom.css"]
    colorscheme = "light"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/fifionachow/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/fifionachow/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/fiona-chow-53477bb4/"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"